name = "devactyl-license"
main = "src/worker.js"
compatibility_date = "2023-06-18"

# [env.production]
# MY_VARIABLE = "production_value"

# [env.staging]
# MY_VARIABLE = "staging_value"

# [env.shared]
# SHARED_VARIABLE = "shared_value"

# wrangler.toml (wrangler v3.79.0^)
[observability]
enabled = true
head_sampling_rate = 1

[vars]
AUTHORIZATION_HEADER = "TWluZUNvcmVATWluZUNvcmVCb3Q="
DISCORD_WEBHOOK = "https://discord.com/api/webhooks/1122225848762765342/K1rir3zwwPFHUhXt_tdPBUL_AupaG_V9oOMj5DKI0_3K9LhJFV6ebRS82tjWM-5-Auag"
PRODUCT_ID = "656663b60d230b4d33a529a9"
PRODUCT_NAME = "Devactyl Bot"
PRODUCT_ICON = "https://user-images.githubusercontent.com/64340067/199940356-7de35553-cb0b-4862-aace-7c21f160dc51.png"
OWNER_ID = "759050921413312532"
REALM_API = "vvSJfWuschlpMGst7InfsQyocK3zKMr18pZHERXw7MkQ1e96xriw1Ewr9RBNHJwz"
REALM_ID = "application-0-tuzpv"
DASHBOARD_URL = "https://devley.yuvaraja.tech"
WS_KEEPALIVE = "60"
VERSION = "1.4"
COLOR = "1002722"