name = "devley"
main = "src/worker.ts"
compatibility_date = "2024-08-02"

# [env.production]
# MY_VARIABLE = "production_value"

# [env.staging]
# MY_VARIABLE = "staging_value"

# [env.shared]
# SHARED_VARIABLE = "shared_value"

# wrangler.toml (wrangler v4.15.0^)
[observability]
enabled = true
head_sampling_rate = 1

[vars]
VERSION = "1.6"
OWNER_ID = "759050921413312532"
DASHBOARD_URL = "https://devley.1he.dev"
WEBSOCKET_URL = "wss://devley-ws.1he.dev"